version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_resume_automation
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: BS@Dhaka
      POSTGRES_DB: resumeautomation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - resume_network

volumes:
  postgres_data:

networks:
  resume_network:
    driver: bridge
